# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b08b28ac27e026c920b7c76a81bfe5fbcb99dd80496920a3e7f3ebad8514e90343be5d6bcc4444a089fbbc38cf7b121c37b3307334886d85714db29d2a591c2

test:
  secret_key_base: 5ffd49eaa2a4ba8a5e95155e3c7d900e94f00c673afd7712326a8a75f15ba4f6fab7e034d3ceade2fe79a33cb5a5e355f1d6dee191db98e667445dcb1a4983c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
